### ISSUE TITLE
Cannot find file during initial `llt` command

### ISSUE THREAD

**Issue by ServerlessSam** [ServerlessLife/lambda-live-debugger#48]
OS: Mac

CDK: 2.143.0

lld: 1.0.0

```
samuellock@Samuels-MacBook-Pro-305 cdk-aurora-lambda % sudo npm install lambda-live-debugger -g
Password:
Sorry, try again.
Password:

added 25 packages in 14s

23 packages are looking for funding
  run `npm fund` for details
samuellock@Samuels-MacBook-Pro-305 cdk-aurora-lambda % lld
Welcome to Lambda Live Debugger 🐞 version 1.0.0.
To keep the project moving forward, please fill out the feedback form at https://forms.gle/v6ekZtuB45Rv3EyW9. Your input is greatly appreciated!
Starting the debugger (ID 75caeecaaff28b5ae6dbf4ea840d940b)...
Error: cannot find /Users/samuellock/Repositories/ss/aws-db-loadtesting/cdk-aurora-lambda/x/restrict-default-security-group-handler/index.js
    at new _CustomResourceProviderBase (eval at <anonymous> (file:///usr/local/lib/node_modules/lambda-live-debugger/dist/frameworks/cdkFrameworkWorker.mjs:32:3), <anonymous>:18029:17)
    at new _RestrictDefaultSgProvider (eval at <anonymous> (file:///usr/local/lib/node_modules/lambda-live-debugger/dist/frameworks/cdkFrameworkWorker.mjs:32:3), <anonymous>:64777:9)
    at Function.getOrCreateProvider (eval at <anonymous> (file:///usr/local/lib/node_modules/lambda-live-debugger/dist/frameworks/cdkFrameworkWorker.mjs:32:3), <anonymous>:64774:47)
    at _Vpc.restrictDefaultSecurityGroup (eval at <anonymous> (file:///usr/local/lib/node_modules/lambda-live-debugger/dist/frameworks/cdkFrameworkWorker.mjs:32:3), <anonymous>:65162:132)
    at new _Vpc (eval at <anonymous> (file:///usr/local/lib/node_modules/lambda-live-debugger/dist/frameworks/cdkFrameworkWorker.mjs:32:3), <anonymous>:65079:194)
    at new CdkAuroraLambdaStack (eval at <anonymous> (file:///usr/local/lib/node_modules/lambda-live-debugger/dist/frameworks/cdkFrameworkWorker.mjs:32:3), <anonymous>:382369:17)
    at eval (eval at <anonymous> (file:///usr/local/lib/node_modules/lambda-live-debugger/dist/frameworks/cdkFrameworkWorker.mjs:32:3), <anonymous>:382476:1)
    at MessagePort.<anonymous> (file:///usr/local/lib/node_modules/lambda-live-debugger/dist/frameworks/cdkFrameworkWorker.mjs:32:3)
Error: CDK worker stopped with exit code 1
    at Worker.<anonymous> (file:///usr/local/lib/node_modules/lambda-live-debugger/dist/frameworks/cdkFramework.mjs:296:28)
    at Worker.emit (node:events:518:28)
    at [kOnExit] (node:internal/worker:315:10)
    at Worker.<computed>.onexit (node:internal/worker:229:20)
```

**Comment by ServerlessLife** [comment]
Hi Sam,

Thank you for reporting the issue.

I think I know what the issue is. CDK makes a mess with their internal lambda handler paths, so I had to resort to some hacking: 
https://github.com/ServerlessLife/lambda-live-debugger/blob/e03d43c67d9775fa095c9c8c3f96917ff7c25ef3/src/frameworks/cdkFrameworkWorker.mjs#L69

I will try to add all those paths, and that will probably solve the issue.

It would help if you share your CDK code so I can validate my solution.

Best regards,

Marko

**Comment by ServerlessLife** [comment]
I managed to reproduce the issue.

**Comment by ServerlessLife** [comment]
The issue is fixed. Can you verify?
