### ISSUE TITLE
Problems with infrastructure/business logic split

### ISSUE THREAD

**Issue by hffmnn** [ServerlessLife/lambda-live-debugger#58]
Hi.

Our repository looks like this

```
- infrastructure
   -  <CDK code lives here>
- service
  -  handler code lives here
```

I think with that layout it is not possible to set up `lld` and use e.g. Breakpoints? 

To discover the lambdas `lld` needs to run in the `infrastructure` subfolder (and that works as expected!). But to execute the debugger (via F5) I also have to run VS Code in the `infrastructure` subfolder and with that, VS Code doesn't have access to the service folder (where I could add breakpoints).

**Comment by markostru** [comment]
Hi Christian,

Thank you very much for submitting the question.

As far as I can see, this is a standard setup for monorepo, and it is supported. So if you run `lld` from the root and set the `subfolder` parameter to `infrastructure`, it should work. You set the `subfolder` as part of the wizard setup or as a CLI parameter.

You also need to run VsCode from the root folder so the VsCode has access to the `infrastructure` and `service` folders.

Best regards,

Marko

**Comment by hffmnn** [comment]
Hi.

Thanks a lot for the quick response. Running from the root (having llb installed in the infrastructure folder) give me this:

```
 ./infrastructure/node_modules/.bin/lld --wizard --verbose
Welcome to Lambda Live Debugger 🐞 version 1.0.6.
To keep the project moving forward, please fill out the feedback form at https://forms.gle/v6ekZtuB45Rv3EyW9. Your input is greatly appreciated!
? Which framework are you using (detected: ?)? cdk
? Would you like to enter CDK context (example: environment=development)? stage=Samwise
? Would you like to enter more CDK context? 
? If you are using monorepo, enter subfolder where the framework is instaled. infrastructure
? Do you want to use observable mode, which just sends events to the debugger and do not use the respose? No
? Would you like to use named AWS profile? 
? Would you like to specify AWS region? eu-west-1
? Would you like to specify AWS role? 
? Would you like to filter which Lambdas to debug? Pick one
Getting resources with 'cdk' framework
[CDK] Entry file: /Users/user/workspace/soundreply/services/how.fm-profile-matching-service/infrastructure/src/bin.ts
[CDK] Context: {
  "@aws-cdk/aws-lambda:recognizeLayerVersion": true,
  "@aws-cdk/core:checkSecretUsage": true,
  "@aws-cdk/core:target-partitions": [
    "aws",
    "aws-cn"
  ],
  "@aws-cdk-containers/ecs-service-extensions:enableDefaultLogDriver": true,
  "@aws-cdk/aws-ec2:uniqueImdsv2TemplateName": true,
  "@aws-cdk/aws-ecs:arnFormatIncludesClusterName": true,
  "@aws-cdk/aws-iam:minimizePolicies": true,
  "@aws-cdk/core:validateSnapshotRemovalPolicy": true,
  "@aws-cdk/aws-codepipeline:crossAccountKeyAliasStackSafeResourceName": true,
  "@aws-cdk/aws-s3:createDefaultLoggingPolicy": true,
  "@aws-cdk/aws-sns-subscriptions:restrictSqsDescryption": true,
  "@aws-cdk/aws-apigateway:disableCloudWatchRole": true,
  "@aws-cdk/core:enablePartitionLiterals": true,
  "@aws-cdk/aws-events:eventsTargetQueueSameAccount": true,
  "@aws-cdk/aws-iam:standardizedServicePrincipals": true,
  "@aws-cdk/aws-ecs:disableExplicitDeploymentControllerForCircuitBreaker": true,
  "@aws-cdk/aws-iam:importedRoleStackSafeDefaultPolicyName": true,
  "@aws-cdk/aws-s3:serverAccessLogsUseBucketPolicy": true,
  "@aws-cdk/aws-route53-patters:useCertificate": true,
  "@aws-cdk/customresources:installLatestAwsSdkDefault": false,
  "@aws-cdk/aws-rds:databaseProxyUniqueResourceName": true,
  "@aws-cdk/aws-codedeploy:removeAlarmsFromDeploymentGroup": true,
  "@aws-cdk/aws-apigateway:authorizerChangeDeploymentLogicalId": true,
  "@aws-cdk/aws-ec2:launchTemplateDefaultUserData": true,
  "@aws-cdk/aws-secretsmanager:useAttachedSecretResourcePolicyForSecretTargetAttachments": true,
  "@aws-cdk/aws-redshift:columnId": true,
  "@aws-cdk/aws-stepfunctions-tasks:enableEmrServicePolicyV2": true,
  "@aws-cdk/aws-ec2:restrictDefaultSecurityGroup": true,
  "@aws-cdk/aws-apigateway:requestValidatorUniqueId": true,
  "@aws-cdk/aws-kms:aliasNameRef": true,
  "@aws-cdk/aws-autoscaling:generateLaunchTemplateInsteadOfLaunchConfig": true,
  "@aws-cdk/core:includePrefixInUniqueNameGeneration": true,
  "@aws-cdk/aws-efs:denyAnonymousAccess": true,
  "@aws-cdk/aws-opensearchservice:enableOpensearchMultiAzWithStandby": true,
  "@aws-cdk/aws-lambda-nodejs:useLatestRuntimeVersion": true,
  "@aws-cdk/aws-efs:mountTargetOrderInsensitiveLogicalId": true,
  "@aws-cdk/aws-rds:auroraClusterChangeScopeOfInstanceParameterGroupWithEachParameters": true,
  "@aws-cdk/aws-appsync:useArnForSourceApiAssociationIdentifier": true,
  "@aws-cdk/aws-rds:preventRenderingDeprecatedCredentials": true,
  "@aws-cdk/aws-codepipeline-actions:useNewDefaultBranchForCodeCommitSource": true,
  "stage": "Samwise",
  "aws:cdk:bundling-stacks": []
}
[CDK] aws-cdk-lib path: /Users/user/workspace/soundreply/services/how.fm-profile-matching-service/infrastructure/node_modules/aws-cdk-lib
[CDK] [Worker] Error Error: No Lambda functions found in the CDK code
    at MessagePort.<anonymous> (file:///Users/user/workspace/soundreply/services/how.fm-profile-matching-service/infrastructure/node_modules/lambda-live-debugger/dist/frameworks/cdkFrameworkWorker.mjs:20:13)
Error: CDK worker stopped with exit code 1
    at Worker.<anonymous> (file:///Users/user/workspace/soundreply/services/how.fm-profile-matching-service/infrastructure/node_modules/lambda-live-debugger/dist/frameworks/cdkFramework.mjs:365:28)
    at Worker.emit (node:events:514:28)
    at [kOnExit] (node:internal/worker:315:10)
    at Worker.<computed>.onexit (node:internal/worker:229:20)
```

The code resolves the entry file correctly `[CDK] Entry file: /Users/user/workspace/soundreply/services/how.fm-profile-matching-service/infrastructure/src/bin.ts` but fails to resolve the lambdas somehow.

Running the same command from the `infrastructure` subfolder works as expected.

Offtopic: Spotted this typo `instaled` in in this question: `? If you are using monorepo, enter subfolder where the framework is instaled.`

**Comment by markostru** [comment]
Thank you for letting me know about the typo.

I think I see a potential bug. 
When you selected:
`Would you like to filter which Lambdas to debug? Pick one` 
it tried to find all the Lambdas, but maybe it did not use all the parameters correctly.

Could you pick `select all`?
Then, when you run, it should use all parameters correctly.

I will try to reproduce the issue in the afternoon.

**Comment by hffmnn** [comment]
When selecting `select all` it finishes the wizard. 

But then, when pressing `F5` in the root this happens:

```
  /usr/bin/env 'NODE_OPTIONS= --require "/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/ms-vscode.js-debug/src/bootloader.js"  --inspect-publish-uid=http' 'VSCODE_INSPECTOR_OPTIONS=:::{"inspectorIpc":"/var/folders/16/crv_8j1x0xjg9qw_z4ksh8g00000gn/T/node-cdp.26208-b57023a6-1.sock","deferredMode":false,"waitForDebugger":"","execPath":"/Users/user/.volta/bin/node","onlyEntrypoint":false,"autoAttachMode":"always","fileCallback":"/var/folders/16/crv_8j1x0xjg9qw_z4ksh8g00000gn/T/node-debug-callback-6b87822ef522a4b3"}' /Users/user/workspace/soundreply/services/some.thing-service/infrastructure/node_modules/.bin/lld 
Debugger attached.
Welcome to Lambda Live Debugger 🐞 version 1.0.6.
To keep the project moving forward, please fill out the feedback form at https://forms.gle/v6ekZtuB45Rv3EyW9. Your input is greatly appreciated!
Parameters: 
 - framework=cdk
 - context=stage=Samwise
 - subfolder=infrastructure
 - region=eu-west-1
 - observable=false
 - verbose=true
 - interval=3000
 - debuggerId=be962f2812f9ac380669b83a196c49b2
 - start=true
NPM module folder: /Users/user/workspace/soundreply/services/some.thing-service/infrastructure/node_modules/lambda-live-debugger/dist
Project folder: /Users/user/workspace/soundreply/services/some.thing-profile-matching-service
Starting the debugger (ID be962f2812f9ac380669b83a196c49b2)...
Changing current folder to /Users/user/workspace/soundreply/services/some.thing-service/infrastructure
Getting resources with 'cdk' framework
[CDK] Entry file: /Users/user/workspace/soundreply/services/some.thing-service/infrastructure/src/bin.ts
[CDK] Context: {
  "@aws-cdk/aws-lambda:recognizeLayerVersion": true,
  "@aws-cdk/core:checkSecretUsage": true,
  "@aws-cdk/core:target-partitions": [
    "aws",
    "aws-cn"
  ],
  "@aws-cdk-containers/ecs-service-extensions:enableDefaultLogDriver": true,
  "@aws-cdk/aws-ec2:uniqueImdsv2TemplateName": true,
  "@aws-cdk/aws-ecs:arnFormatIncludesClusterName": true,
  "@aws-cdk/aws-iam:minimizePolicies": true,
  "@aws-cdk/core:validateSnapshotRemovalPolicy": true,
  "@aws-cdk/aws-codepipeline:crossAccountKeyAliasStackSafeResourceName": true,
  "@aws-cdk/aws-s3:createDefaultLoggingPolicy": true,
  "@aws-cdk/aws-sns-subscriptions:restrictSqsDescryption": true,
  "@aws-cdk/aws-apigateway:disableCloudWatchRole": true,
  "@aws-cdk/core:enablePartitionLiterals": true,
  "@aws-cdk/aws-events:eventsTargetQueueSameAccount": true,
  "@aws-cdk/aws-iam:standardizedServicePrincipals": true,
  "@aws-cdk/aws-ecs:disableExplicitDeploymentControllerForCircuitBreaker": true,
  "@aws-cdk/aws-iam:importedRoleStackSafeDefaultPolicyName": true,
  "@aws-cdk/aws-s3:serverAccessLogsUseBucketPolicy": true,
  "@aws-cdk/aws-route53-patters:useCertificate": true,
  "@aws-cdk/customresources:installLatestAwsSdkDefault": false,
  "@aws-cdk/aws-rds:databaseProxyUniqueResourceName": true,
  "@aws-cdk/aws-codedeploy:removeAlarmsFromDeploymentGroup": true,
  "@aws-cdk/aws-apigateway:authorizerChangeDeploymentLogicalId": true,
  "@aws-cdk/aws-ec2:launchTemplateDefaultUserData": true,
  "@aws-cdk/aws-secretsmanager:useAttachedSecretResourcePolicyForSecretTargetAttachments": true,
  "@aws-cdk/aws-redshift:columnId": true,
  "@aws-cdk/aws-stepfunctions-tasks:enableEmrServicePolicyV2": true,
  "@aws-cdk/aws-ec2:restrictDefaultSecurityGroup": true,
  "@aws-cdk/aws-apigateway:requestValidatorUniqueId": true,
  "@aws-cdk/aws-kms:aliasNameRef": true,
  "@aws-cdk/aws-autoscaling:generateLaunchTemplateInsteadOfLaunchConfig": true,
  "@aws-cdk/core:includePrefixInUniqueNameGeneration": true,
  "@aws-cdk/aws-efs:denyAnonymousAccess": true,
  "@aws-cdk/aws-opensearchservice:enableOpensearchMultiAzWithStandby": true,
  "@aws-cdk/aws-lambda-nodejs:useLatestRuntimeVersion": true,
  "@aws-cdk/aws-efs:mountTargetOrderInsensitiveLogicalId": true,
  "@aws-cdk/aws-rds:auroraClusterChangeScopeOfInstanceParameterGroupWithEachParameters": true,
  "@aws-cdk/aws-appsync:useArnForSourceApiAssociationIdentifier": true,
  "@aws-cdk/aws-rds:preventRenderingDeprecatedCredentials": true,
  "@aws-cdk/aws-codepipeline-actions:useNewDefaultBranchForCodeCommitSource": true,
  "stage": "Samwise",
  "aws:cdk:bundling-stacks": []
}
[CDK] aws-cdk-lib path: /Users/user/workspace/soundreply/services/some.thing-service/infrastructure/node_modules/aws-cdk-lib
[CDK] [Worker] Started
[Worker undefined] Received message {
  compileOutput: '/Users/user/workspace/soundreply/services/some.thing-service.lldebugger/compiledCdk.cjs'
}
[CDK] [Worker] Error Error: No Lambda functions found in the CDK code
    at MessagePort.<anonymous> (file:///Users/user/workspace/soundreply/services/some.thing-service/infrastructure/node_modules/lambda-live-debugger/dist/frameworks/cdkFrameworkWorker.mjs:20:13)
Error: CDK worker stopped with exit code 1
    at Worker.<anonymous> (file:///Users/user/workspace/soundreply/services/some.thing-service/infrastructure/node_modules/lambda-live-debugger/dist/frameworks/cdkFramework.mjs:365:28)
    at Worker.emit (node:events:514:28)
    at [kOnExit] (node:internal/worker:315:10)
    at Worker.<computed>.onexit (node:internal/worker:229:20)
    at Worker.callbackTrampoline (node:internal/async_hooks:130:17)
Waiting for the debugger to disconnect...
```

The `launch.json` looks like this:

```
{
  "version": "0.2.0",
  "configurations": [
    {
      "name": "Lambda Live Debugger",
      "type": "node",
      "request": "launch",
      "runtimeExecutable": "/Users/user/workspace/soundreply/services/some.thing-service/infrastructure/node_modules/.bin/lld",
      "runtimeArgs": [],
      "console": "integratedTerminal",
      "skipFiles": [
        "<node_internals>/**"
      ],
      "env": {}
    }
  ]
}
```

**Comment by ServerlessLife** [comment]
I give up.
I tried to install and set up the environment in every way I could. It works for me, no matter how I do it. I actually found some other bugs along the way, but that should not be the reason for your issues.

So, you are doing something different, and I can not figure out what.

Can you do the following steps:
1. Install it globally: `sudo npm install lambda-live-debugger -g`
2. run `lld -w -v` in the project root. No `npx` prefix. Choose "select all" to debug all Lambdas.
3. run `lld` to start the debugger. Let's not use F5 this time.

Your code for creating Lambda in CDK probably looks something like this:
```typescript
    const myLambda = new lambda_nodejs.NodejsFunction(
      this,
      'MyLambda',
      {
        entry: '/service/handler.ts'),
        runtime: lambda.Runtime.NODEJS_20_X
      },
    );
```
This is like "the default" way. But any other setup also works for me. 

The best way would be if you could provide a sample. :pray:

**Comment by hffmnn** [comment]
When installing and running `lld` globally I get the same results: The wizards runs through, starting `lld` gives the same error. Even with version `1.0.7`.

I will try to make a reproducible project setup.

**Comment by ServerlessLife** [comment]
I would be extremely grateful for the sample project.

**Comment by hffmnn** [comment]
Here you go: https://github.com/hffmnn/lld-example

I didn't commit my `lld` config files but documented what I did in the README. Hope that helps.

**Comment by ServerlessLife** [comment]
Thank you very much for providing the sample.

It has to do something with yarn.

This is a really weird error:
- It works if I use yarn
- It works if I use npm and delete `yarn.lock`
- It does not work when npm and do not delete `yarn.lock`

I will keep exploring.

**Comment by hffmnn** [comment]
> It works if I use yarn

Hm, what did you do to make it work with `yarn`?
After checking out the repository you ran which commands?

**Comment by ServerlessLife** [comment]
I did not do anything. 
I went through the procedure above. 
First, I tried with npm, and that failed because I did not delete `yarn.lock`

I did not have more time to explore. I will try to do that letter in a day.

**Comment by hffmnn** [comment]
> I did not do anything.
> I went through the procedure above.

So you tried the procedure with a global install? But how did you use `yarn` then?

**Comment by markostru** [comment]
For yarn, I installed it locally on the root folder.

I will try to debug it more thoroughly in the evening.

**Comment by hffmnn** [comment]
Just for documentation, here's what I did at the root of the project:

```
yarn init -y
yarn lld --wizard --verbose
yarn lld
```

When running this everything works as expected. Also VS Code `F5` debugging works.

And I must say: Seeing a breakpoint get hit from a deployed lambda feels like magic 🪄

**Comment by ServerlessLife** [comment]
O great. You made it to work.

I am still surprised that it did not work initially. I managed to find the point in the code where it failed, but I did not have more time.

If you have any other questions or issues, do not hesitate.
