### ISSUE TITLE
Initial Setup failure: Non-object value specified in functions array

### ISSUE THREAD

**Issue by imewish** [ServerlessLife/lambda-live-debugger#70]
```

Welcome to Lambda Live Debugger 🐞 version 1.1.2.
Parameters: 
 - context=undefined
 - interval=3000
 - verbose=true
 - debuggerId=b9065f108590b0a4c58164b216d2e903
 - start=true
NPM module folder: /Users/devs/.nvm/versions/node/v20.13.1/lib/node_modules/lambda-live-debugger/dist
Project folder: /Users/wish/Documents/work/socket/my-app
Starting the debugger (ID b9065f108590b0a4c58164b216d2e903)...
[CDK] This is not a CDK project. /Users/wish/Documents/work/socket/my-app/cdk.json not found
Getting resources with 'sls' framework
[SLS] Configuration path: /Users/wish/Documents/work/socket/my-app/serverless.yml
[SLS] Configuration: {
  "service": "my-api",
  "frameworkVersion": "3",
  "useDotenv": true,
  "provider": {
    "name": "aws",
    "runtime": "nodejs18.x",
    "stage": "${opt:stage, 'dev'}",
    "region": "${opt:region, 'us-east-1'}",
    "versionFunctions": false,
    "logRetentionInDays": "${param:logRetentionInDays}",
    "deploymentBucket": {
      "blockPublicAccess": true,
      "skipPolicySetup": false,
      "name": "socket-${self:provider.stage}-slsdeployment-artifacts"
    },
    "tags": {
      "service": "${self:service}",
      "stage": "${self:provider.stage}"
    },
    "environment": {
    },

  },
  "package": {
    "individually": true
  },
  "params": {
    "prod": "${file(./sls.params.prod.yml)}",
    "dev": "${file(./sls.params.dev.yml)}"
  },
  "custom": {
    "alerts": "${file(./sls.alerts.yml)}",
    "lumigo": {
      "token": "${self:custom.envs.LUMIGO_TOKEN}",
      "nodePackageManager": "yarn"
    },
    "envs": "${ssm:/aws/reference/secretsmanager/backend/${self:provider.stage}/microservices/env}",
    "esbuild": {
      "bundle": true,
      "minify": false,
      "nativeZip": true,
      "packager": "yarn",
      "treeShaking": true,
      "concurrency": 1
    },
  },
  "functions": [
    "${file(./app/handlers/myapp/sls.yml)}","
  ],
  "plugins": [
    "serverless-offline",
    "serverless-plugin-aws-alerts",
    "serverless-esbuild"
  ]
}
[SLS] Configuration filename: /Users/dev/Documents/work/socket/my-app/serverless.yml
Error: Error running Serverless. Non-object value specified in functions array: ${file(./app/handlers/myapp/sls.yml)}
    at SlsFramework.getLambdas (file:///Users/dev/.nvm/versions/node/v20.13.1/lib/node_modules/lambda-live-debugger/dist/frameworks/slsFramework.mjs:115:19)
    at async Object.getLambdas (file:///Users/dev/.nvm/versions/node/v20.13.1/lib/node_modules/lambda-live-debugger/dist/resourceDiscovery.mjs:43:21)
    at async Object.discoverLambdas (file:///Users/dev/.nvm/versions/node/v20.13.1/lib/node_modules/lambda-live-debugger/dist/configuration.mjs:115:26)
    at async run (file:///Users/dev/.nvm/versions/node/v20.13.1/lib/node_modules/lambda-live-debugger/dist/lldebugger.mjs:54:5) {
  [cause]: ServerlessError: Non-object value specified in functions array: ${file(./app/handlers/myapp/sls.yml)}
      at /Users/dev/.nvm/versions/node/v20.13.1/lib/node_modules/serverless/lib/classes/service.js:248:19
      at Array.reduce (<anonymous>)
      at /Users/dev/.nvm/versions/node/v20.13.1/lib/node_modules/serverless/lib/classes/service.js:243:31
      at Array.forEach (<anonymous>)
      at Service.mergeArrays (/Users/dev/.nvm/versions/node/v20.13.1/lib/node_modules/serverless/lib/classes/service.js:241:32)
      at Serverless.run (/Users/dev/.nvm/versions/node/v20.13.1/lib/node_modules/serverless/lib/serverless.js:165:20)
      at SlsFramework.getLambdas (file:///Users/dev/.nvm/versions/node/v20.13.1/lib/node_modules/lambda-live-debugger/dist/frameworks/slsFramework.mjs:112:30)
      at async Object.getLambdas (file:///Users/dev/.nvm/versions/node/v20.13.1/lib/node_modules/lambda-live-debugger/dist/resourceDiscovery.mjs:43:21)
      at async Object.discoverLambdas (file:///Users/dev/.nvm/versions/node/v20.13.1/lib/node_modules/lambda-live-debugger/dist/configuration.mjs:115:26)
      at async run (file:///Users/dev/.nvm/versions/node/v20.13.1/lib/node_modules/lambda-live-debugger/dist/lldebugger.mjs:54:5) {
    code: 'LEGACY_CONFIGURATION_PROPERTY_MERGE_INVALID_INPUT',
    decoratedMessage: undefined
  }
}
```

**Comment by imewish** [comment]
Sample function structure in sls.yml

```
myfunction:
  handler: app/handlers/myapp/app.handler
  timeout: 30
  events:
    - http:
        path: /v2/service/myapp/build-dex-step/myapp
        method: get
        authorizer: aws_iam
  vpc: ${param:vpc}
  ```

**Comment by ServerlessLife** [comment]
Thank you very much @imewish for reporting the issue.

I managed to reproduce the problem and I am trying to resolve it.

**Comment by ServerlessLife** [comment]
Hi @imewish.

As you saw from the bot message :point_up:, the issue is resolved.

This was not supported until now:
```
functions:
  - ${file(./sls.yml)}
```

Let me know if you have any other questions or have stumbled upon any other issues.
